"""Public virtual-fund contracts used by cross-module financial use cases."""

from app.modules.funds.schemas import (
    AllocationCreateRequest,
    AllocationPreviewResponse,
    FundEventResponse,
    FundHistoryResponse,
    FundMovementResponse,
    FundSummaryResponse,
    RedistributionCreateRequest,
)
from app.modules.funds.service import (
    FundArchivedMutationError,
    FundBalanceError,
    FundCoverageError,
    FundNotFoundError,
    account_has_fund_history,
    allocation_preview_with_free_balance,
    create_allocation_with_free_balance,
    create_redistribution_with_physical_balances,
    event_response,
    event_responses,
    fund_names,
    history_source_ids,
    operation_fund_movements,
    replace_operation_movements,
    reserved_balance,
    summary_with_physical_balances,
    validate_account_coverage,
)

__all__ = [
    "FundBalanceError",
    "FundArchivedMutationError",
    "FundCoverageError",
    "FundNotFoundError",
    "AllocationCreateRequest",
    "AllocationPreviewResponse",
    "FundEventResponse",
    "FundHistoryResponse",
    "FundMovementResponse",
    "FundSummaryResponse",
    "RedistributionCreateRequest",
    "account_has_fund_history",
    "allocation_preview_with_free_balance",
    "create_allocation_with_free_balance",
    "create_redistribution_with_physical_balances",
    "event_response",
    "event_responses",
    "operation_fund_movements",
    "fund_names",
    "history_source_ids",
    "replace_operation_movements",
    "reserved_balance",
    "summary_with_physical_balances",
    "validate_account_coverage",
]
