"""Public virtual-fund contracts used by cross-module financial use cases."""

from decimal import Decimal
from uuid import UUID

from sqlalchemy.orm import Session

from app.modules.funds.schemas import (
    AllocationCreateRequest,
    AllocationItem,
    AllocationPreviewResponse,
    FundCreateRequest,
    FundEventResponse,
    FundHistoryResponse,
    FundMovementResponse,
    FundReleaseRequest,
    FundReleaseResponse,
    FundReserveReleaseRequest,
    FundResponse,
    FundSummaryResponse,
    FundTransferCreateRequest,
    FundUpdateRequest,
    RedistributionCreateRequest,
    TransferAllocationCreateRequest,
    TransferAllocationResponse,
)
from app.modules.funds.service import (
    DynamicFundTargetsRequiredError,
    FundAllocationUnavailableError,
    FundArchiveBalanceError,
    FundArchivedMutationError,
    FundBalanceError,
    FundConflictError,
    FundCoverageError,
    FundDistributionState,
    FundNotFoundError,
    FundTargetCapacityError,
    LegacyTransferAllocationMatch,
    account_has_fund_history,
    allocation_preview_with_free_balance,
    archive_fund,
    complete_percentage_allocations,
    create_allocation_with_free_balance,
    create_fund,
    create_fund_release,
    create_fund_transfer,
    create_managed_fund,
    create_redistribution_with_physical_balances,
    dynamic_capacity_allocations,
    dynamic_percentages,
    event_response,
    event_responses,
    existing_fund_release,
    fund_names,
    get_fund_response,
    history_source_ids,
    link_fund_release,
    lock_operation_dependent_allocation,
    locked_active_funds,
    locked_percentage_allocation_preview_with_free_balance,
    locked_percentage_definitions,
    managed_fund_snapshot,
    operation_fund_movements,
    operation_has_fund_release,
    operation_has_managed_reservation,
    percentage_allocations,
    post_managed_fund,
    rebalance_reserve,
    release_reserve,
    remove_operation_dependent_events,
    remove_operation_reserve_distributions,
    replace_operation_movements,
    reserve_balance,
    reserve_balances,
    reserved_balance,
    reserved_balances,
    snapshot_dynamic_percentages_as_manual,
    summary_with_physical_balances,
    update_fund,
    validate_account_coverage,
    validate_dynamic_targets,
)


def create_fund_definition(
    session: Session,
    *,
    name: str,
    description: str | None,
    percentage: Decimal,
    target_amount: Decimal | None,
) -> UUID:
    """Create a Funds-owned definition without exposing its private model."""
    return create_fund(
        session,
        name=name,
        description=description,
        percentage=percentage,
        target_amount=target_amount,
    ).id


def fund_response(session: Session, fund_id: UUID) -> FundResponse:
    return get_fund_response(session, fund_id)


__all__ = [
    "FundArchiveBalanceError",
    "create_managed_fund",
    "managed_fund_snapshot",
    "post_managed_fund",
    "operation_has_managed_reservation",
    "FundReleaseRequest",
    "FundReleaseResponse",
    "create_fund_release",
    "existing_fund_release",
    "link_fund_release",
    "operation_has_fund_release",
    "FundConflictError",
    "FundBalanceError",
    "DynamicFundTargetsRequiredError",
    "FundArchivedMutationError",
    "FundAllocationUnavailableError",
    "FundCoverageError",
    "FundConflictError",
    "FundNotFoundError",
    "FundTargetCapacityError",
    "LegacyTransferAllocationMatch",
    "AllocationCreateRequest",
    "AllocationItem",
    "AllocationPreviewResponse",
    "FundEventResponse",
    "FundCreateRequest",
    "FundTransferCreateRequest",
    "FundUpdateRequest",
    "FundHistoryResponse",
    "FundMovementResponse",
    "FundReserveReleaseRequest",
    "FundResponse",
    "FundSummaryResponse",
    "RedistributionCreateRequest",
    "TransferAllocationCreateRequest",
    "TransferAllocationResponse",
    "account_has_fund_history",
    "archive_fund",
    "allocation_preview_with_free_balance",
    "complete_percentage_allocations",
    "create_allocation_with_free_balance",
    "create_fund_definition",
    "create_fund_transfer",
    "create_redistribution_with_physical_balances",
    "dynamic_capacity_allocations",
    "event_response",
    "event_responses",
    "operation_fund_movements",
    "rebalance_reserve",
    "remove_operation_dependent_events",
    "release_reserve",
    "remove_operation_reserve_distributions",
    "reserve_balance",
    "reserve_balances",
    "fund_names",
    "fund_response",
    "history_source_ids",
    "locked_active_funds",
    "lock_operation_dependent_allocation",
    "locked_percentage_definitions",
    "locked_percentage_allocation_preview_with_free_balance",
    "percentage_allocations",
    "dynamic_percentages",
    "FundDistributionState",
    "snapshot_dynamic_percentages_as_manual",
    "validate_dynamic_targets",
    "replace_operation_movements",
    "reserved_balance",
    "reserved_balances",
    "summary_with_physical_balances",
    "update_fund",
    "validate_account_coverage",
]
